### ISSUE TITLE
运行起来 等了很久 没反应呢

### ISSUE THREAD

**Issue by rehe0x** [ycwoo/DHTSpider#1]
运行起来 等了很久 没反应呢

**Comment by rehe0x** [comment]
![image](https://user-images.githubusercontent.com/19343192/50749682-6f5aa680-127b-11e9-9b70-4f2dceaf9d40.png)

**Comment by ycwoo** [comment]
需要放在有公网ip的机器上

**Comment by rehe0x** [comment]
> 需要放在有公网ip的机器上

嗯 可以爬数据了  有个情况   现在爬数据很慢   我3台服务器  一天才几百条

**Comment by ycwoo** [comment]
这个和网速也有关系，对下行带宽要求更高些，你的带宽是多大的？config.py里MAX_NODE_SIZE和DOWNLOAD_THREAD可以调大些如果cpu内存比较给力的话。

**Comment by rehe0x** [comment]
腾讯云 1c 2g 1m  这样的  第一次跑起来  很快 一会儿就几千条  后面停了几天    后来再启动跑的就非常慢    我再研究下   感谢

**Comment by ycwoo** [comment]
1m的带宽偏小了，而且如果是国内的节点，有些节点ip会被gfw ban掉，我的是在linode上运行的，一小时能稳定7000以上。关于慢的问题，这个启动的时候会寻找节点等等，等找到足够多的节点以后，和其他节点建立起稳定的连接就很快了。
